-- Initialize vim by pulling all configuration files from ./lua
require('options')
require('plugins')
require('lsp_config')
require('telescope_nvim')
require('treesitter')
require('nvim_cmp')
require('nvim_dap')
require('nvim_dap_virtual_text')
require('neovim_cmake')
require('nvim_autopairs')
