-- Initialize vim by pulling all configuration files from ./lua
require('options')
require('plugins')
require('lsp_config')
require('telescope_nvim')
require('treesitter')
require('nvim_cmp')
require('nvim_dap')
require('neovim_cmake')
require('nvim_autopairs')
require('mason_nvim')
require('lsp_colors')
require('nvim_web_devicons')
require('trouble_nvim')
require('null_ls')
