vim.o.autoindent = true
vim.o.colorcolumn = "80"
vim.o.ignorecase = true
vim.o.number = true
vim.o.shiftwidth = 4
vim.o.smartcase = true
vim.o.softtabstop = 4 -- negative value means use same as shiftwidth
vim.o.termguicolors = true
vim.o.undofile = true
vim.o.wrap = false
